//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scaffef.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTask
    {
        public int TaskID { get; set; }
        public int ProjectID { get; set; }
        public string Title { get; set; }
        public string EndUser { get; set; }
        public string AssignedTo { get; set; }
        public string StatusName { get; set; }
        public string SubCategoryName { get; set; }
        public string PriorityName { get; set; }
        public string GroupName { get; set; }
    }
}
